export const SERVICE_POLICIES = [
  "EL CLIENTE ACEPTA LAS POLITICAS DE SERVICIO DE CLICK.COM DEL CARIBE Y ACEPTA QUE A TRAVES DE NUESTROS PROCEDIMIENTOS SE REALICE LA REPARACION Y/O DIAGNOSTICO DE SU EQUIPO DE COMPUTO AL SER ENTREGADO A NUESTRA EMPRESA.",
  "LA REVISION O DIAGNOSTICO DEL EQUIPO REPARABLE O NO REPARABLE ES DE: CPU/PC: $300.00 PESOS, LAPTOP: $500 PESOS, IMPRESORA LASER E INYECCION DE TINTA $300.00, TABLET $200.00, PRECIOS MAS IVA, EN NUESTRAS INSTALACIONES.",
  "EN CASO DE ACEPTAR EL SERVICIO PREVIA COTIZACION, NO SE COBRARA EL DIAGNOSTICO, UNICAMENTE EL COSTO DE LA REPARACION POR MANO DE OBRA Y REFACCIONES.",
  "EL TIEMPO DE GARANTIA EN LA REPARACION O MANO DE OBRA ES DE 7 DIAS NATURALES.",
  "EL TIEMPO DE GARANTIA EN REFACCIONES DEPENDERA DEL FABRICANTE O DEL PROVEEDOR.",
  "EL TIEMPO DE GARANTIA NO APLICA EN CASO DE ELIMINACION DE VIRUS Y CUALQUIER SOFTWARE QUE EL CLIENTE TRAIGA PARA INSTALAR.",
  "NO SE ENTREGA EL EQUIPO EN CASO DE NO PRESENTAR LA ORDEN DE SERVICIO CORRESPONDIENTE, EN CASO DE EXTRAVIO PRESENTAR DOCUMENTOS QUE AVALEN LA PROPIEDAD DEL MISMO.",
  "CLICK.COM DEL CARIBE NO SE HACE RESPONSABLE DE LOS ACCESORIOS Y DANOS FISICOS (GOLPES, RAYADURAS) NO DECLARADOS EN LA ORDEN DE SERVICIO.",
  "LA EMPRESA CLICK.COM DEL CARIBE Y SU REPRESENTANTE LEGAL PERSONA FISICA JUAN GABRIEL CUPUL HUU NO SE HACE RESPONSABLE DEL SOFTWARE ORIGINAL Y NO ORIGINAL INSTALADOS, ASI COMO TAMPOCO Y/O DESPUES DE DOS MESES DE HABER SIDO CONCLUIDO Y AVISADO AL CLIENTE DEL DIAGNOSTICO Y/O REPARACION.",
  "LA FORMA DE PAGO DEL SERVICIO ES DE CONTADO, CON TARJETA DE DEBITO O CREDITO (MAS EL 2.5%), CHEQUE A NOMBRE DE JUAN GABRIEL CUPUL HUU, Y SE ENTREGARA EL EQUIPO CUANDO EL PAGO ESTE EN FIRME EN LA CUENTA.",
  "VERIFIQUE QUE EL EQUIPO RECIBIDO ESTE DE ACUERDO A LO DECLARADO EN LA ORDEN DE SERVICIO, YA QUE NO SE ACEPTARA ALGUNA RECLAMACION POSTERIOR A LA FECHA DE ENTREGA.",
  "EN CASO CONTRARIO TENDRA UN COSTO DE $300.00 PESOS DE RESGUARDO POR DIA Y LA EMPRESA NO SE HACE RESPONSABLE DEL EQUIPO.",
];
